/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Controller.ControllerTextoDisciplina;
import Model.Disciplina;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhona
 */
public class JDisciplina extends javax.swing.JFrame {
    
    ControllerTextoDisciplina controle = new ControllerTextoDisciplina();    
    String modoInterface;
    
    public void LoadTable (){
        DefaultTableModel modelo = new DefaultTableModel (new Object[]{"Turma","Nome"},0);
        
        for (int i=0 ; i<controle.lista.size();i++){
            Object linha[] = new Object []{controle.lista.get(i).getTurma(),controle.lista.get(i).getNome()};
            modelo.addRow(linha);
        
        }
        tblDisc.setModel(modelo);
        tblDisc.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblDisc.getColumnModel().getColumn(1).setPreferredWidth(200);        
        tblDisc.setModel(modelo);
    
    }

    /**
     * Creates new form JDisciplina
     */
    public JDisciplina() {
        initComponents();
        setLocationRelativeTo(null);
        modoInterface = "Navegar";
        ManipulaInterface();
    }
    public void ManipulaInterface(){
        switch(modoInterface){
            case "Navegar":
                btnDisc_Salvar.setEnabled(false);
                btnDisc_Cancelar.setEnabled(false);
                textDisc_Turma.setEnabled(false);
                textDisc_Nome.setEnabled(false);
                btnDisc_Novo.setEnabled(true);
                btnDisc_Editar.setEnabled(false);
                btnDisc_Excluir.setEnabled(false);
                btnDisc_Gravar.setEnabled(false);
                btnDisc_Ler.setEnabled(true);
                break;
            case "Novo":
                btnDisc_Salvar.setEnabled(true);
                btnDisc_Cancelar.setEnabled(true);
                textDisc_Turma.setEnabled(true);
                textDisc_Nome.setEnabled(true);
                btnDisc_Novo.setEnabled(false);
                btnDisc_Editar.setEnabled(false);
                btnDisc_Excluir.setEnabled(false);
                btnDisc_Gravar.setEnabled(false);
                btnDisc_Ler.setEnabled(true);
                
                break;
                
            case "Editar":
                btnDisc_Salvar.setEnabled(true);
                btnDisc_Cancelar.setEnabled(true);
                textDisc_Turma.setEnabled(true);
                textDisc_Nome.setEnabled(true);
                btnDisc_Novo.setEnabled(true);
                btnDisc_Editar.setEnabled(false);
                btnDisc_Excluir.setEnabled(false);
                btnDisc_Gravar.setEnabled(true);
                btnDisc_Ler.setEnabled(true);
                break;
                
            case "Excluir":
                btnDisc_Salvar.setEnabled(false);
                btnDisc_Cancelar.setEnabled(false);
                textDisc_Turma.setEnabled(false);
                textDisc_Nome.setEnabled(false);
                btnDisc_Novo.setEnabled(true);
                btnDisc_Editar.setEnabled(false);
                btnDisc_Excluir.setEnabled(false);
                btnDisc_Gravar.setEnabled(true);
                btnDisc_Ler.setEnabled(true);
                break;
                
            case "Selecao":
                btnDisc_Salvar.setEnabled(false);
                btnDisc_Cancelar.setEnabled(false);
                textDisc_Turma.setEnabled(false);
                textDisc_Nome.setEnabled(false);
                btnDisc_Novo.setEnabled(true);
                btnDisc_Editar.setEnabled(true);
                btnDisc_Excluir.setEnabled(true);
                btnDisc_Gravar.setEnabled(true);
                btnDisc_Ler.setEnabled(true);
                break;
            default: System.out.println("Modo inválido");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDisc_Editar = new javax.swing.JButton();
        TabelaDisc = new javax.swing.JScrollPane();
        tblDisc = new javax.swing.JTable();
        btnDisc_Excluir = new javax.swing.JButton();
        btnDisc_Voltar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblTurma = new javax.swing.JLabel();
        textDisc_Turma = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        textDisc_Nome = new javax.swing.JTextField();
        btnDisc_Salvar = new javax.swing.JButton();
        btnDisc_Cancelar = new javax.swing.JButton();
        btnDisc_Novo = new javax.swing.JButton();
        btnDisc_Gravar = new javax.swing.JButton();
        btnDisc_Ler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Disciplina");

        btnDisc_Editar.setText("Editar");
        btnDisc_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisc_EditarActionPerformed(evt);
            }
        });

        tblDisc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Turma", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisc.setRequestFocusEnabled(false);
        tblDisc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDiscMouseClicked(evt);
            }
        });
        TabelaDisc.setViewportView(tblDisc);
        if (tblDisc.getColumnModel().getColumnCount() > 0) {
            tblDisc.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblDisc.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        btnDisc_Excluir.setText("Excluir");
        btnDisc_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisc_ExcluirActionPerformed(evt);
            }
        });

        btnDisc_Voltar.setText("Voltar");
        btnDisc_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisc_VoltarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Inserir/Editar Disciplina"));

        lblTurma.setText("Turma:");

        lblNome.setText("Nome:");

        btnDisc_Salvar.setText("Salvar");
        btnDisc_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisc_SalvarActionPerformed(evt);
            }
        });

        btnDisc_Cancelar.setText("Cancelar");
        btnDisc_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisc_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(lblTurma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnDisc_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDisc_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textDisc_Turma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDisc_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTurma)
                    .addComponent(textDisc_Turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDisc_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisc_Cancelar)
                    .addComponent(btnDisc_Salvar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnDisc_Novo.setText("Novo");
        btnDisc_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisc_NovoActionPerformed(evt);
            }
        });

        btnDisc_Gravar.setText("Gravar");
        btnDisc_Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisc_GravarActionPerformed(evt);
            }
        });

        btnDisc_Ler.setText("Ler");
        btnDisc_Ler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisc_LerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnDisc_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnDisc_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDisc_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDisc_Gravar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDisc_Ler, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDisc_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(TabelaDisc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(TabelaDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDisc_Gravar)
                        .addComponent(btnDisc_Ler))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDisc_Novo)
                        .addComponent(btnDisc_Editar)
                        .addComponent(btnDisc_Excluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisc_Voltar)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisc_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisc_EditarActionPerformed
        
        controle.editarDisciplina(textDisc_Turma.getText(),textDisc_Nome.getText());
        LoadTable();
        modoInterface = "Editar";
        ManipulaInterface();
        textDisc_Turma.setText("");
        textDisc_Nome.setText("");
    }//GEN-LAST:event_btnDisc_EditarActionPerformed

    private void tblDiscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDiscMouseClicked
        int index = tblDisc.getSelectedRow();
        if(index >= 0 && index<controle.lista.size()){
            Disciplina disc = controle.lista.get(index);
            textDisc_Turma.setText(disc.getTurma());
            textDisc_Nome.setText(disc.getNome());
        }
    }//GEN-LAST:event_tblDiscMouseClicked

    private void btnDisc_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisc_ExcluirActionPerformed
        controle.excluirDisciplina(textDisc_Nome.getText());
        LoadTable();
        modoInterface = "Excluir";
        ManipulaInterface();
        textDisc_Turma.setText("");
        textDisc_Nome.setText("");
    }//GEN-LAST:event_btnDisc_ExcluirActionPerformed

    private void btnDisc_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisc_VoltarActionPerformed
        new JMenuInicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDisc_VoltarActionPerformed

    private void btnDisc_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisc_SalvarActionPerformed
        controle.addDisciplina(textDisc_Turma.getText(), textDisc_Nome.getText());          
        LoadTable();
        modoInterface = "Selecao";
        ManipulaInterface();
        textDisc_Turma.setText("");
        textDisc_Nome.setText("");
    }//GEN-LAST:event_btnDisc_SalvarActionPerformed

    private void btnDisc_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisc_CancelarActionPerformed
        textDisc_Turma.setText("");
        textDisc_Nome.setText("");
        modoInterface = "Selecao";
    }//GEN-LAST:event_btnDisc_CancelarActionPerformed

    private void btnDisc_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisc_NovoActionPerformed
        textDisc_Turma.setText("");
        textDisc_Nome.setText("");
        modoInterface = "Novo";
        ManipulaInterface();
        
    }//GEN-LAST:event_btnDisc_NovoActionPerformed

    private void btnDisc_GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisc_GravarActionPerformed
        controle.gravarDisciplina();
        LoadTable();
        modoInterface = "Gravar";
        ManipulaInterface();
    }//GEN-LAST:event_btnDisc_GravarActionPerformed

    private void btnDisc_LerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisc_LerActionPerformed
        controle.lerDisciplina();
        LoadTable();
        modoInterface = "Ler";
        ManipulaInterface();
    }//GEN-LAST:event_btnDisc_LerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDisciplina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TabelaDisc;
    private javax.swing.JButton btnDisc_Cancelar;
    private javax.swing.JButton btnDisc_Editar;
    private javax.swing.JButton btnDisc_Excluir;
    private javax.swing.JButton btnDisc_Gravar;
    private javax.swing.JButton btnDisc_Ler;
    private javax.swing.JButton btnDisc_Novo;
    private javax.swing.JButton btnDisc_Salvar;
    private javax.swing.JButton btnDisc_Voltar;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTurma;
    private javax.swing.JTable tblDisc;
    private javax.swing.JTextField textDisc_Nome;
    private javax.swing.JTextField textDisc_Turma;
    // End of variables declaration//GEN-END:variables
}
